config/routes.rb
Rails.application.routes.draw do

  get '/home' => 'quizzes#index'
  
  get 'sessions/create' => 'sessions#welcome'
  get 'sessions/welcome' => 'sessions#welcome', :as => :welcome

  get 'users/resend' => 'users#resend', :as => :resend
  post 'users/resend' => 'sessions#new'
  root 'quizzes#index'
  get '/about' => 'pages#about'

  get 'users/index'
  post 'users/index' => 'users#index'
 
  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post 'logout' => 'sessions#new'
  resources :quizzes, only: :index
  resources :users 
  resources :attempts
  resources :scores

resources :account_activations, only: [:edit]

post '/attempts/new' => 'attempts#new'
 
 

end

app/controllers/quizzes_controller.rb
class QuizzesController < ApplicationController
before_action :require_user, only: [:show, :new, :create, :index]

def index
  @user = current_user
  @quizzes = Quiz.all
end

private
def quiz_params
    params.require(:quiz).permit(:id, :name, :description, user_attributes: [:id, :first_name, :last_name, :email, :password,
                                   :password_confirmation], attempts_attributes: [:id, :quiz_id, :user_id, :finished, questions_attributes: [ :id, :test_id, :unit_id, :category_id, :test_code, :page, :number], answers_attributes: [ :id, :letter, :user_id, :question_id, :option_id, :correct ]])
end

end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/views/quizzes/index.html.erb
<div class="main">

    <h1>Welcome to Pravina Prep!</h1>
    <p>Hello <%= current_user.first_name %>! Start by taking a pretest!</p>

    <div class="btn-group-vertical btn-group-lg btn-hover" role="group" aria-label="...">
       <% @quizzes.each do |q| %>
    <%= link_to q.name, new_attempt_path(quiz_id: q.id), :method => 'new', :class => "btn btn-default"%>
    <% end %>
</div>
</div>