config/routes.rb
Rails.application.routes.draw do

  get '/home' => 'quizzes#index'
  
  get 'sessions/create' => 'sessions#welcome'
  get 'sessions/welcome' => 'sessions#welcome', :as => :welcome

  get 'users/resend' => 'users#resend', :as => :resend
  post 'users/resend' => 'sessions#new'
  root 'quizzes#index'
  get '/about' => 'pages#about'

  get 'users/index'
  post 'users/index' => 'users#index'
 
  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post 'logout' => 'sessions#new'
  resources :quizzes, only: :index
  resources :users 
  resources :attempts
  resources :scores

resources :account_activations, only: [:edit]

post '/attempts/new' => 'attempts#new'
 
 

end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
  belongs_to :quiz
  belongs_to :user
  has_many :answers, :dependent => :destroy
  has_many :questions, through: :answers
  has_many :scores
  #validates_uniqueness_of :user_id, scope: :quiz_id
  accepts_nested_attributes_for :questions, :answers, :scores

  def correct_answers
    return self.answers.where(:correct => true)
  end

  def incorrect_answers
    return self.answers.where(:correct => false)
  end

private
  def attempt_params
    params.require(:attempt).permit(:id, :quiz_id, :user_id, :finished, questions_attributes: [ :id, :test_id, :unit_id, :category_id, :test_code, :page, :number], answers_attributes: [ :id, :letter, :user_id, :question_id, :option_id, :correct ])
  end
end

app/controllers/attempts_controller.rb
class AttemptsController < ApplicationController
before_action :require_user, only: [:show, :new, :create, :index]
#before_action :load_attempt, only: [:show]


  def index
    @attempt = Attempt.all
  end

  def show
    @attempt = Attempt.find_by(id: params[:id])
    @user = current_user
    @quiz = Quiz.find_by(id: params[:quiz_id])
  end

  def new
    @user = current_user
    @quiz = Quiz.find_by(id: params[:quiz_id])
    @attempt = Attempt.new
    if @quiz.name == 'Pretest'
      @attempt.questions = Question.where(test_code: '72C').order('number')
    elsif @quiz.name == 'Mean, Median, and Mode'
      @attempt.questions = Question.where(unit_id: 2).order('number')
    elsif @quiz.name == 'Unanswered'
      #@attempt.questions = Question.includes(:answers).where.not(answers: {user_id: current_user.id  correct: true}) 
      @attempt.questions = Question.where('id NOT IN (SELECT question_id FROM answers WHERE correct = true and user_id = ?)', current_user.id).order('number')
    end
    @attempt.answers.build
    # respond_to do |format|
    #   format.html # new.html.erb
    #   format.json { redirect_to @user }
    #end
  end


  def create
    @user = current_user
    @quiz = Quiz.find_by(id: params[:quiz_id])
    @attempt = Attempt.new(attempt_params)
    #@attempt.answers = answers_attributes.map{ |a| Answer.new(a)}
    @attempt.answers.each do |a|
      if a.letter == a.correct_answer
      a.correct = true
      else
      a.correct = false
      end
    end
    if @attempt.valid? && @attempt.save
      redirect_to attempt_path(@attempt, user_id: current_user.id, quiz_id: @attempt.quiz_id)
    else
      render :new
    end
  end

private

  def load_attempt
    @attempt = Attempt.find(params[:id])
  end

  def attempt_params
    params.require(:attempt).permit(:id, :quiz_id, :user_id, :finished, questions_attributes: [ :id, :test_id, :unit_id, :category_id, :test_code, :page, :number], answers_attributes: [ :id, :letter, :user_id, :question_id, :option_id, :correct, :correct_answer ])
  end
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/views/attempts/_form.html.erb
<li>
  <p>
    Test Code: <%= question.test_code %>, 
    page <%= question.page %>, 
    number: <%= question.number %> 
    <%= f.fields_for :answers, question.answers.new do |a| %> Answer: <%= a.text_field :letter %></p>
  <%= a.hidden_field :user_id, :value => current_user.id %>
  <% end %>
</li>

app/views/attempts/new.html.erb
<div class="main">
<h2>
  <%= @quiz.name %>
</h2> 
<p><%= @quiz.description %></p>

<%= form_for(@attempt) do |f| %> 
<%= f.hidden_field :user_id, :value => current_user.id %>
<%= f.hidden_field :quiz_id, :value => @quiz.id %>
<div style="columns: 3">
    <% f.object.questions.each do |q| %>
   <%= f.fields_for :answers, @attempt.answers.new do |a| %>
            <p>
              Test Code: <%= q.test_code %>, 
              page <%= q.page %>, 
              #<%= q.number %> 
            Answer: 
            <%= a.text_field :letter, :size=>"1x1", :maxlength=>"1"  %></p>
            <%= a.hidden_field :user_id, :value => current_user.id %>
            <%= a.hidden_field :question_id, :value => q.id %>
            <%= a.hidden_field :correct_answer, :value => q.correct_answer %>
        <% end %>
<% end %>
</div>
<div><%= submit_tag("Submit", :class => "btn") %></div>
<% end %>  
 </div>

<script>
$(".submit").on("click", function(){
     $.ajax({
        url: "/scores",
        type: "POST",
        data: {attempt_id: <%= @attempt.id %>, answer: _.map($("input:checked"), function(choice){return choice.getAttribute("grade")}) },
        
        success: function(response) {
            $("body").append($("<div class ='score'>SCORE:" + response.value + "% </div>"))
            $(".quiz").remove(); 
            $(".submit").remove();
        }
      });
  })

  </script>

app/views/attempts/show.html.erb
<h2>
  <%= @quiz.name %>
  <p><small><%= @quiz.description %></small></p>
</h2>
    <ol>   
      <% @attempt.answers.each do |a| %>
          <li>
              <p>
              Test Code: <%= a.question.test_code %>, 
              page <%= a.question.page %>, 
              #<%= a.question.number %>, 
              <% if a.letter.blank? %>
              You left this answer blank!  Don't forget:  YOU SHOULD NEVER LEAVE AN ANSWER BLANK ON THE ACT!!!
              <% elsif a.correct == true %>  
              You chose: <%= a.letter.upcase %>  Congratulations!  That was the correct answer!  
              <% else %>  
              You chose: <%= a.letter.upcase %>  Good try, but that's not quite right.  The correct answer is <%= a.correct_answer.upcase %>.  *Explanation here*
              <% end %>
              </p>
          </li> 
    <% end %>
  </ol>
  <%= link_to 'Click here to see your score!', scores_path(user_id: current_user.id, attempt_id: @attempt.id, quiz_id: @quiz.id), class: 'btn btn-default btn-sm', method: :create %>