config/routes.rb
Rails.application.routes.draw do

  get '/home' => 'quizzes#index'
  
  get 'sessions/create' => 'sessions#welcome'
  get 'sessions/welcome' => 'sessions#welcome', :as => :welcome

  get 'users/resend' => 'users#resend', :as => :resend
  post 'users/resend' => 'sessions#new'
  root 'quizzes#index'
  get '/about' => 'pages#about'

  get 'users/index'
  post 'users/index' => 'users#index'
 
  get '/signup' => 'users#new'

  get '/login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  post 'logout' => 'sessions#new'
  resources :quizzes, only: :index
  resources :users 
  resources :attempts
  resources :scores

resources :account_activations, only: [:edit]

post '/attempts/new' => 'attempts#new'
 
 

end

app/models/answer.rb
class Answer < ActiveRecord::Base
  belongs_to :user
  belongs_to :attempt
  belongs_to :option
  belongs_to :question
  #validates_uniqueness_of :user_id, scope: :question_id

  after_create :characterize_answer

  def new
    @answer = Answer.new
  end

  def create
    @answer = Answer.new(params[:answer])
  end


private

  def characterize_answer
    if self.letter == self.correct_answer
    self.correct = true
    else
    self.correct = false
    end
  end

  def answer_params
    params.require(:answer).permit( :id, :letter, :user_id, :question_id, :option_id, :correct, :correct_answer )
  end
end

app/models/attempt.rb
class Attempt < ActiveRecord::Base
  belongs_to :quiz
  belongs_to :user
  has_many :answers, :dependent => :destroy
  has_many :questions, through: :answers
  has_many :scores
  #validates_uniqueness_of :user_id, scope: :quiz_id
  accepts_nested_attributes_for :questions, :answers, :scores

  def correct_answers
    return self.answers.where(:correct => true)
  end

  def incorrect_answers
    return self.answers.where(:correct => false)
  end

private
  def attempt_params
    params.require(:attempt).permit(:id, :quiz_id, :user_id, :finished, questions_attributes: [ :id, :test_id, :unit_id, :category_id, :test_code, :page, :number], answers_attributes: [ :id, :letter, :user_id, :question_id, :option_id, :correct ])
  end
end

app/models/category.rb
class Category < ActiveRecord::Base
belongs_to :test
belongs_to :unit
has_many :questions
accepts_nested_attributes_for :questions
end

app/models/option.rb
class Option < ActiveRecord::Base
  belongs_to :question
  has_many :answers

  scope :correct,   -> { where(correct: true)  }
  scope :incorrect, -> { where(correct: false) }

  # def correct?
  #   return (self.correct == true)
  # end

end

app/models/question.rb
class Question < ActiveRecord::Base
belongs_to :test
belongs_to :unit
belongs_to :category
has_many :attempts, through: :answers
has_many :options
has_many :answers
accepts_nested_attributes_for :options, :answers, :attempts

private
  def question_params
    params.require(:question).permit( :id, :test_id, :unit_id, :category_id, :test_code, :page, :number, answers_attributes: [ :id, :letter, :user_id, :question_id, :option_id, :correct ])
  end
end

app/models/quiz.rb
class Quiz < ActiveRecord::Base
  has_many :attempts
  has_many :questions
  has_many :users, through: :attempts
  has_many :scores
  accepts_nested_attributes_for :questions, :users, :attempts, :scores

private

  def quiz_params
    params.require(:quiz).permit(:name, :description, questions_attributes: [ :id, :test_code, :page, :number ])
  end
  
end

app/models/score.rb
class Score < ActiveRecord::Base
  belongs_to :user
  belongs_to :attempt
  belongs_to :quiz
  #validates_uniqueness_of :user_id, scope: :quiz_id
end

app/models/test.rb
class Test < ActiveRecord::Base
  has_many :units
  has_many :categories, through: :units
  has_many :questions, through: :categories
  accepts_nested_attributes_for :units, :categories, :questions
end

app/models/unit.rb
class Unit < ActiveRecord::Base
  belongs_to :test
  has_many :categories
  has_many :questions, through: :categories
  accepts_nested_attributes_for :categories, :questions
end

app/models/user.rb
class User < ActiveRecord::Base
	attr_accessor :remember_token, :activation_token
  before_save do
    self.email.downcase!
    self.first_name.capitalize!
    self.last_name.capitalize!
  end
  before_create :create_activation_digest
	validates :first_name, presence: true, length: { maximum: 50 }
	validates :last_name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, 
					  length: {maximum: 255}, 
					  format: { with: VALID_EMAIL_REGEX }, 
					  uniqueness: { case_sensitive: false }
	has_secure_password
	validates :password, presence: true, length: { minimum: 6 }
   has_many :attempts, dependent: :destroy
   has_many :questions, through: :answers
   has_many :answers, through: :attempts
   has_many :scores, through: :attempts
   has_many :quizzes, through: :attempts
   accepts_nested_attributes_for :attempts, :questions, :answers, :scores, :quizzes

	def self.new_token
    	SecureRandom.urlsafe_base64
  end

  def self.digest(string)
    	cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    	BCrypt::Password.create(string, cost: cost)
  end

  def authenticated?(attribute, token)
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(token)
  end

# Forgets a user.
  def forget
    update_attribute(:remember_digest, nil)
  end

  def resend_activation
    update_activation_digest
    UserMailer.account_activation(self).deliver_now
  end

  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end
  
	private

    # Creates and assigns the activation token and digest.
    def create_activation_digest
      self.activation_token  = User.new_token
      self.activation_digest = User.digest(activation_token)
    end

    def update_activation_digest
      self.activation_token  = User.new_token
      update_attribute(:activation_digest, User.digest(activation_token))
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

end

app/controllers/units_controller.rb
class UnitsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/attempts_helper.rb
module AttemptsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/quizzes_helper.rb
module QuizzesHelper
end

app/helpers/scores_helper.rb
module ScoresHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  # Returns true if the user is logged in, false otherwise.
  def logged_in?
    !current_user.nil?
  end
  
end

app/helpers/units_helper.rb
module UnitsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
  
  <title>Pravina Prep</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag 'application.css' %>
    <link href="http://fonts.googleapis.com/css?family=Playfair+Display" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Muli" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Raleway:400, 600' rel='stylesheet' type='text/css'>
    <%= javascript_include_tag "application.js", "data-turbolinks-track" => true %>
    <%= javascript_include_tag 'http://ajax.aspnetcdn.com/ajax/jquery.validate/1.9/jquery.validate.min.js' %>
    <%= javascript_include_tag "bootstrap.min.js" %>
    <%= csrf_meta_tags %>

    
</head>

<body>
  <!--navigation -->
  <div class="navbar navbar-inverse navbar-static-top navbar-custom" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header"> 
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> 
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/home">
          <span><img alt="Pravina Test Prep" src="https://s3.amazonaws.com/pravina/Pravina-Logo.gif" height="40px" width='40px'></span>  Online ACT Prep
        </a>
      </div>  
      <div class="navbar-collapse collapse"> 
        <ul class="nav navbar-nav navbar-right">
          <% if current_user %> 
            <li><a href="/home" ><%= current_user.first_name %></a></li> 
            <li><%= link_to "Log Out", logout_path, method: "delete" %></li> 
          <% else %> 
<!--             <li><a href="/about">About</a></li>  -->
              <li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                Sign Up 
                <strong class="caret"></strong>
              </a>
              <div class="dropdown-menu" style="padding: 15px; padding-bottom: 15px;">
                <!-- Sign Up form here -->

                <%= render partial: 'users/new' %>
              </div>
            </li>         
            <li class="dropdown">
              <a class="dropdown-toggle" href="#" data-toggle="dropdown">
                Login 
                <strong class="caret"></strong>
              </a>
              <div class="dropdown-menu" style="padding: 15px; padding-bottom: 15px;">
                <!-- Login form here -->

                <%= render partial: 'sessions/new' %>
              </div>

            </li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>          


  <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>" role="alert" ><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span><%= message %></div>
  <% end %> 

<%= yield %>
</body>

app/views/pages/about.html.erb
<div class="jumbotron">

  <h1>Pravina Prep</h1>
  <p>Your home for individualized, web based ACT instruction</p> 
<a href="/signup" class="btn-main">Get Started</a>
</div>
<div class="main">
    <h1>About Us</h1>
  <div class="row-fluid">
  <div class="span4">
    <h3>Majid Hasan</h3>
    <img class="resize" src="https://s3.amazonaws.com/pravina/Majid.jpg">
    <p>Majid is a lawyer (more here).</p>
  </div>
  <div class="span4">
    <h3>Rachel Steelman</h3>
    <img class="resize" src="https://s3.amazonaws.com/pravina/Rachel.jpg">
    <p>Rachel is a physics and chemistry teacher with a masters in physics from University of Missouri - Kansas City and a masters in education from Pittsburg State University.</p>
  </div>
</div>
</div>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger"><span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>